GET http://localhost:5001/api/users/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjg1NTY3OWEwMDM3NzU1NDg0Y2RiMzZmIiwibmFtZSI6IkRhbmllbCBTb2xleW1hbmkiLCJlbWFpbCI6ImRhbmllbC5zb2xleW1hbmkxMkBnbWFpbC5jb20iLCJhZ2UiOjE4LCJsb2NhdGlvbiI6IkJldGhsZWhlbSwgUEEiLCJtb250aGx5SW5jb21lIjoyMDAwfSwiaWF0IjoxNzUxMzgxMDkwLCJleHAiOjE3NTEzODQ2OTB9.MXh9pQ7RMG8VwoUHT20qrz_a4UuoA3WjQrOZfi-F1Bc

{
    "email" : "daniel.soleymani12@gmail.com", 
    "password" : "D7S7nnpp"
}
